### ISSUE TITLE
投稿の読み上げの不具合 (F-Droid)

### ISSUE THREAD

**Issue by yakitama** [tateisu/SubwayTooter#258]
投稿の読み上げについて不具合があり困っております。ご確認ください。

● 報告する現象と再現手順
1. カラム設定の「投稿を読み上げる」的なチェックボックスを ON にする。
2. 「TextToSpeech の初期化中...」というトーストメッセージが表示される。
3. すぐに、アプリが異常終了する。

以後、アプリを起動するたびに、2 と 3 を繰り返します。アプリのデータを初期化することで起動できるようになります。

● 期待する動作
- (優先) 少なくとも、データの削除なしで復帰できるようにする。
- 当該チェックボックスを ON にすると、新たに受信した投稿を読み上げる。
- (代替) もしくは、これが Google サービスに依存しており、F-Droid で配信するために意図的にそのライブラリを呼ばないようにしている場合は、異常終了しないようにする。

● 確認したアプリのバージョンと環境 
- 5.542-noFcm (F-Droid)
- Pixel 8 Pro
- Android 14 
  - セキュリティアップデート: 2023年12月5日
  - Google Play システムアップデート: 2023年11月1日

他に必要な情報がありましたらご指摘ください。

**Comment by tateisu** [comment]
Pixel 7a で確認してクラッシュした。収集したログ
```
AndroidRuntime           E  FATAL EXCEPTION: main
Process: jp.juggler.subwaytooter.noFcm, PID: 16745
java.lang.SecurityException: jp.juggler.subwaytooter.noFcm: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified
when a receiver isn't being registered exclusively for system broadcasts
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
    at android.os.Parcel.createException(Parcel.java:3041)
    at android.os.Parcel.readException(Parcel.java:3024)
    at android.os.Parcel.readException(Parcel.java:2966)
    at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
    at jp.juggler.subwaytooter.AppState$enableSpeech$1$ttsInitListener$1$1.invoke(AppState.kt:430)
    at jp.juggler.subwaytooter.AppState$enableSpeech$1$ttsInitListener$1$1.invoke(AppState.kt:395)
    at jp.juggler.util.coroutine.LooperUtilsKt.runOnMainLooper(LooperUtils.kt:15)
    at jp.juggler.subwaytooter.AppState$enableSpeech$1.invokeSuspend$lambda$0(AppState.kt:395)
    at jp.juggler.subwaytooter.AppState$enableSpeech$1.$r8$lambda$4n8PMJRgKDtpL_BBOeiVIwhR7ns(Unknown Source:0)
    at jp.juggler.subwaytooter.AppState$enableSpeech$1$$ExternalSyntheticLambda0.onInit(Unknown Source:4)
    at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0(TextToSpeech.java:934)
    at android.speech.tts.TextToSpeech.$r8$lambda$goj8UKjdOAM21kdYLRXRNDpSxxI(Unknown Source:0)
    at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda1.run(Unknown Source:4)
    at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:943)
    at android.speech.tts.TextToSpeech.-$$Nest$mdispatchOnInit(Unknown Source:0)
    at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2324)
    at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2284)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8177)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
    at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
    at android.os.Binder.execTransactInternal(Binder.java:1339)
    at android.os.Binder.execTransact(Binder.java:1275)
```

**Comment by tateisu** [comment]
Android 14 の「動作の変更点: Android 14 以上をターゲットとするアプリ」
「実行時に登録されるブロードキャスト レシーバでは、エクスポート動作を指定する必要がある」
https://developer.android.com/about/versions/14/behavior-changes-14?hl=ja#runtime-receivers-exported

の対応漏れっぽい

**Comment by tateisu** [comment]
変更後
```
ContextCompat.registerReceiver(
    context,
    ttsReceiver,
    IntentFilter(TextToSpeech.ACTION_TTS_QUEUE_PROCESSING_COMPLETED),
    ContextCompat.RECEIVER_EXPORTED,
    // RECEIVER_NOT_EXPORTED だと読み上げ完了を受け取れない
    // ContextCompat.RECEIVER_NOT_EXPORTED,
)
```

動作確認して次のログが出ることを確認
```
AppState:ttsReceiver onReceive action=android.speech.tts.TTS_QUEUE_PROCESSING_COMPLETED
```

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v5.544 を試してください。

**Comment by yakitama** [comment]
- 起動しない状態に陥った Pixel 8 Pro に、noFcm の apk を更新インストールしました。
  - データ削除はしていません。
- 起動するようになりました。
- 正常に読み上げが作動しました。

ご対応ありがとうございます。
